### ISSUE TITLE
data.can_trade没有效果

### ISSUE THREAD

**Issue by firefirejuly** [JaysonAlbert/cn_zipline#1]
我用数据回测的时候，发现can_trade完全没有调用，没有判断涨跌停，也没有跳过停牌日期。

**Comment by JaysonAlbert** [comment]
zipline的can_trade没办法检测到停牌股票，只能检测到未上市的股票，他的can_trade是拿last_price（往前找第一个不是nan的收盘价），判断是不是nan。所以，如果用pre_close填充停牌的话，需要用volume为0来判断，如果停牌用nan填充的话，应该直接用close为nan判断。ricequant是pre_close填充，用volume为0来判断.

**Comment by JaysonAlbert** [comment]
所以，目前来讲我应该会参考ricequant的做法。

**Comment by JaysonAlbert** [comment]
用can_trade只能用来判断是否已经上市，以及是否已经退市这两种情况，判断停牌要用data.is_stale(stock)，来判断。非停牌就是not data.is_stale(stock)
